#!/bin/sh
# EXAMPLE: podcast-itunes-search methodisch inkorrekt

searchterm=$(echo "$@" | tr " " "+")
wget -q --no-check-certificate -O- "https://itunes.apple.com/search?term=$searchterm&entity=podcast" | jq -r ".results[] | .trackName, .feedUrl"
